---
resources:

- name: automation
  type: git
  source:
    uri: ((automation_pipelines_repo))
    branch: ((automation_pipelines_branch))

jobs:
- name: bootstrap
  public: false
  serial: true
  plan:
  - aggregate:
    - get: automation
      trigger: true
  - task: configure
    file: automation/deployments/pcf/gcp/pipeline/task.yml
    params:
      CONCOURSE_URL: ((concourse_url))
      CONCOURSE_USER: ((concourse_user))
      CONCOURSE_PASSWORD: ((concourse_password))
      AUTOS3_URL: ((autos3_url))
      AUTOS3_ACCESS_KEY: ((autos3_access_key))
      AUTOS3_SECRET_KEY: ((autos3_secret_key))
      GOOGLE_PROJECT: ((google_project))
      GOOGLE_CREDENTIALS_JSON: ((google_credentials_json))
      GOOGLE_REGION: ((google_region))
      BOOTSTRAP_STATE_BUCKET: ((bootstrap_state_bucket))
      BOOTSTRAP_STATE_PREFIX: ((bootstrap_state_prefix))
      VPC_DNS_ZONE: ((vpc_dns_zone))
      ENVIRONMENTS: ((environments))
      PCF_PAS_RUNTIME_TYPE: ((pcf_pas_runtime_type))
      PRODUCTS: ((product))
      UNPAUSE_INSTALL_PIPELINE: ((unpause_install_pipeline))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      SET_START_STOP_SCHEDULE: ((set_start_stop_schedule))