---
jobs:
- name: bootstrap
  public: false
  serial: true
  on_success:
    do:
    - get: job_info
    - task: job_failed_alert
      file: automation/lib/inceptor/tasks/queue_job_email/task.yml
      params: 
        BUCKET: pcf
        EMAIL_QUEUE_PATH: email-queue
        AUTOS3_URL: ((autos3_url))
        AUTOS3_ACCESS_KEY: ((autos3_access_key))
        AUTOS3_SECRET_KEY: ((autos3_secret_key))
        SUBJECT_PRE: ((vpc_name)) bootstrap FAILED
        JOB_STATUS: failed

  # on_failure:
  #   aggregate:

  plan:
  - aggregate:
    - get: automation
      trigger: true
  - task: configure
    file: automation/deployments/pcf/gcp/pipeline/task.yml
    params:
      CONCOURSE_URL: ((concourse_url))
      CONCOURSE_USER: ((concourse_user))
      CONCOURSE_PASSWORD: ((concourse_password))
      AUTOS3_URL: ((autos3_url))
      AUTOS3_ACCESS_KEY: ((autos3_access_key))
      AUTOS3_SECRET_KEY: ((autos3_secret_key))
      CAPS_EMAIL: ((caps_email))
      NOTIFICATION_EMAIL: ((notification_email))
      SMTP_HOST: ((smtp_host))
      SMTP_PORT: ((smtp_port))
      GOOGLE_PROJECT: ((google_project))
      GOOGLE_CREDENTIALS_JSON: ((google_credentials_json))
      GOOGLE_REGION: ((google_region))
      BOOTSTRAP_STATE_BUCKET: ((bootstrap_state_bucket))
      BOOTSTRAP_STATE_PREFIX: ((bootstrap_state_prefix))
      VPC_NAME: ((vpc_name))
      VPC_DNS_ZONE: ((vpc_dns_zone))
      ENVIRONMENTS: ((environments))
      PRODUCTS: ((product))
      UNPAUSE_INSTALL_PIPELINE: ((unpause_install_pipeline))
      OPSMAN_USERNAME: ((opsman_admin_username))
      OPSMAN_PASSWORD: ((opsman_admin_password))
      SET_START_STOP_SCHEDULE: ((set_start_stop_schedule))

- name: notification
  public: false
  serial: true

  plan:
  - get: automation
  - task: prepare_job_email
    file: automation/lib/inceptor/tasks/prepare_job_email/task.yml
    params:
      CONCOURSE_URL: ((concourse_url))
      CONCOURSE_USER: ((concourse_user))
      CONCOURSE_PASSWORD: ((concourse_password))
      AUTOS3_URL: ((autos3_url))
      AUTOS3_ACCESS_KEY: ((autos3_access_key))
      AUTOS3_SECRET_KEY: ((autos3_secret_key))
      BUCKET: pcf
      EMAIL_QUEUE_PATH: email-queue
      SMTP_HOST: ((smtp_host))
      SMTP_PORT: ((smtp_port))
      EMAIL_FROM: ((caps_email))
      EMAIL_TO: ((notification_email))      
  - task: send_job_emails
    file: automation/lib/inceptor/tasks/send_job_emails/task.yml

resources:

- name: automation
  type: git
  source:
    uri: ((automation_pipelines_repo))
    branch: ((automation_pipelines_branch))

- name: job_info
  type: smuggler
  source:
    commands:
      check: |
        echo "$(date +%s)" > ${SMUGGLER_OUTPUT_DIR}/versions
      in: |
        cat <<EOF > $SMUGGLER_DESTINATION_DIR/job_info
        export BUILD_ID='${BUILD_ID}'
        export BUILD_NAME='${BUILD_NAME}'
        export BUILD_JOB_NAME='${BUILD_JOB_NAME}'
        export BUILD_PIPELINE_NAME='${BUILD_PIPELINE_NAME}'
        export BUILD_TEAM_NAME='${BUILD_TEAM_NAME}'
        export ATC_EXTERNAL_URL='${ATC_EXTERNAL_URL}'
        EOF

resource_types:

- name: smuggler
  type: docker-image
  source:
    repository: redfactorlabs/concourse-smuggler-resource
    tag: alpine
